"""add pipeline_runs opportunities

Revision ID: ec842cb13056
Revises: e925b8f6e000
Create Date: 2026-06-15 15:44:10.341482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec842cb13056'
down_revision: Union[str, Sequence[str], None] = 'e925b8f6e000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('prd_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_project_id'), 'pipeline_runs', ['project_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_run_id'), 'opportunities', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_run_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_pipeline_runs_project_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
